# Generated by Django 3.2.3 on 2021-05-22 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DegSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.TextField(blank=True)),
                ('skilllevel', models.TextField(blank=True)),
                ('skilltype', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.TextField(blank=True)),
                ('branch', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('startDate', models.DateField(blank=True)),
                ('endDate', models.DateField(blank=True)),
                ('ispresent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(blank=True)),
                ('position', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('startDate', models.DateField(blank=True)),
                ('endDate', models.DateField(blank=True)),
                ('ispresent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.TextField(blank=True)),
                ('skilllevel', models.TextField(blank=True)),
                ('skilltype', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeySkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.TextField(blank=True)),
                ('skilllevel', models.TextField(blank=True)),
                ('skilltype', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='personalProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('name', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('tech', models.TextField(blank=True)),
                ('startDate', models.DateField(blank=True)),
                ('endDate', models.DateField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techName', models.TextField(blank=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.personalprojects')),
            ],
        ),
    ]
