# Generated by Django 3.2.3 on 2021-05-22 23:33

from django.db import migrations, models
import portfolioapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to=portfolioapp.models.photo_path)),
                ('name', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('tech', models.TextField(blank=True)),
                ('startDate', models.DateField(blank=True)),
                ('endDate', models.DateField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='personalprojects',
            name='logo',
            field=models.ImageField(null=True, upload_to=portfolioapp.models.photo_path),
        ),
    ]
