# Generated by Django 3.2.3 on 2021-05-23 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0006_about_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='portfolioapp.personalprojects'),
        ),
    ]
