# Generated by Django 3.2.3 on 2021-05-23 10:48

from django.db import migrations, models
import portfolioapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0007_alter_technology_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='logo',
            field=models.FileField(null=True, upload_to=portfolioapp.models.photo_path),
        ),
        migrations.AlterField(
            model_name='personalprojects',
            name='logo',
            field=models.FileField(null=True, upload_to=portfolioapp.models.photo_path),
        ),
        migrations.AlterField(
            model_name='recentwork',
            name='logo',
            field=models.FileField(null=True, upload_to=portfolioapp.models.photo_path),
        ),
    ]
