# Generated by Django 3.2.3 on 2021-05-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0008_auto_20210523_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprojects',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalprojects',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recentwork',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recentwork',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
