# Generated by Django 3.2.3 on 2021-05-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0009_auto_20210523_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
