# Generated by Django 3.2.3 on 2021-05-23 11:20

from django.db import migrations, models
import portfolioapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0010_auto_20210523_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='logo',
            field=models.FileField(null=True, upload_to=portfolioapp.models.photo_path),
        ),
        migrations.AddField(
            model_name='experience',
            name='logo',
            field=models.FileField(null=True, upload_to=portfolioapp.models.photo_path),
        ),
    ]
