# Generated by Django 3.2.3 on 2021-05-23 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0011_auto_20210523_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techName', models.TextField(blank=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies2', to='portfolioapp.personalprojects')),
            ],
        ),
    ]
