# Generated by Django 3.2.3 on 2021-05-23 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0012_technology2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology2',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies2', to='portfolioapp.recentwork'),
        ),
    ]
