# Generated by Django 3.2.3 on 2021-05-23 20:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0014_auto_20210524_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='personalprojects',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
