# Generated by Django 3.2.3 on 2021-05-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0015_auto_20210524_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='btn',
            field=models.TextField(null=True),
        ),
    ]
