# Generated by Django 3.2.3 on 2021-05-24 09:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0016_notification_btn'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='shortDescription',
            field=ckeditor.fields.RichTextField(max_length=175, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='shortDescription',
            field=ckeditor.fields.RichTextField(max_length=175, null=True),
        ),
        migrations.AddField(
            model_name='personalprojects',
            name='shortDescription',
            field=ckeditor.fields.RichTextField(max_length=175, null=True),
        ),
        migrations.AddField(
            model_name='recentwork',
            name='shortDescription',
            field=ckeditor.fields.RichTextField(max_length=175, null=True),
        ),
    ]
