# Generated by Django 3.2.3 on 2021-05-24 10:37

from django.db import migrations, models
import portfolioapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0017_auto_20210524_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprojects',
            name='backgroundImage',
            field=models.FileField(null=True, upload_to=portfolioapp.models.photo_path),
        ),
        migrations.AddField(
            model_name='recentwork',
            name='backgroundImage',
            field=models.FileField(null=True, upload_to=portfolioapp.models.photo_path),
        ),
    ]
