# Generated by Django 3.2.3 on 2021-06-02 18:37

from django.db import migrations, models
import portfolioapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0019_auto_20210524_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(null=True, upload_to=portfolioapp.models.photo_path)),
                ('url', models.URLField(null=True)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='companiesWorkedFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(null=True, upload_to=portfolioapp.models.photo_path)),
                ('url', models.URLField(null=True)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subHeading', models.CharField(max_length=120, null=True)),
                ('comment', models.TextField()),
                ('image', models.FileField(null=True, upload_to=portfolioapp.models.photo_path)),
            ],
        ),
        migrations.CreateModel(
            name='sectionEnableDisable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial', models.BooleanField(default=True)),
                ('companies', models.BooleanField(default=True)),
                ('aboutus', models.BooleanField(default=True)),
                ('socialIcons', models.BooleanField(default=True)),
                ('certification', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='socialIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta', models.URLField(null=True)),
                ('yt', models.URLField(null=True)),
                ('fb', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
                ('github', models.URLField(null=True)),
                ('linkedin', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('greetingTxt', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('shortDescription', models.CharField(max_length=1000)),
                ('resumeLink', models.URLField(help_text='Upload it somewhere like google drive and paste the link here.')),
                ('logo', models.FileField(null=True, upload_to=portfolioapp.models.photo_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='degskills',
            name='skilllevel',
        ),
        migrations.RemoveField(
            model_name='degskills',
            name='skilltype',
        ),
        migrations.RemoveField(
            model_name='extraskills',
            name='skilllevel',
        ),
        migrations.RemoveField(
            model_name='extraskills',
            name='skilltype',
        ),
        migrations.RemoveField(
            model_name='keyskills',
            name='skilllevel',
        ),
        migrations.RemoveField(
            model_name='keyskills',
            name='skilltype',
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='degskills',
            name='skillExperience',
            field=models.CharField(blank=True, help_text='Enter year of experience or Intermediate, Beginner, and Expert.', max_length=15),
        ),
        migrations.AddField(
            model_name='degskills',
            name='skillLevel',
            field=models.TextField(blank=True, choices=[('intermediate', 'Intermediate'), ('expert', 'Expert'), ('beginner', 'Beginner')], help_text='Choose skill Level to show color accordingly', max_length=15),
        ),
        migrations.AddField(
            model_name='extraskills',
            name='skillExperience',
            field=models.CharField(blank=True, help_text='Enter year of experience or Intermediate, Beginner, and Expert.', max_length=15),
        ),
        migrations.AddField(
            model_name='extraskills',
            name='skillLevel',
            field=models.TextField(blank=True, choices=[('intermediate', 'Intermediate'), ('expert', 'Expert'), ('beginner', 'Beginner')], help_text='Choose skill Level to show color accordingly', max_length=15),
        ),
        migrations.AddField(
            model_name='keyskills',
            name='skillExperience',
            field=models.CharField(blank=True, help_text='Enter year of experience or Intermediate, Beginner, and Expert.', max_length=15),
        ),
        migrations.AddField(
            model_name='keyskills',
            name='skillLevel',
            field=models.TextField(blank=True, choices=[('intermediate', 'Intermediate'), ('expert', 'Expert'), ('beginner', 'Beginner')], help_text='Choose skill Level to show color accordingly', max_length=15),
        ),
        migrations.AlterField(
            model_name='technology',
            name='techName',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('Java', 'Java'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Bootstrap', 'Bootstrap'), ('PostgresSQL', 'PostgresSQL'), ('Django', 'Django'), ('PHP', 'PHP'), ('MongoDB', 'MongoDB'), ('Docker', 'Docker'), ('Javascript', 'Javascript'), ('jQuery', 'jQuery'), ('ReactJS', 'ReactJS'), ('NodeJS', 'NodeJS'), ('SQLite', 'SQLite'), ('REST API', 'REST API'), ('WordPress', 'WordPress'), ('Drupal', 'Drupal'), ('Magento', 'Magento'), ('Figma', 'Figma'), ('C', 'C'), ('C++', 'C++')], max_length=100),
        ),
        migrations.AlterField(
            model_name='technology2',
            name='techName',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('Java', 'Java'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Bootstrap', 'Bootstrap'), ('PostgresSQL', 'PostgresSQL'), ('Django', 'Django'), ('PHP', 'PHP'), ('MongoDB', 'MongoDB'), ('Docker', 'Docker'), ('Javascript', 'Javascript'), ('jQuery', 'jQuery'), ('ReactJS', 'ReactJS'), ('NodeJS', 'NodeJS'), ('SQLite', 'SQLite'), ('REST API', 'REST API'), ('WordPress', 'WordPress'), ('Drupal', 'Drupal'), ('Magento', 'Magento'), ('Figma', 'Figma'), ('C', 'C'), ('C++', 'C++')], max_length=100),
        ),
    ]
