# Generated by Django 3.2.3 on 2021-06-06 16:10

from django.db import migrations, models
import portfolioapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0021_auto_20210603_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='meta_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('tags', models.TextField()),
                ('img', models.FileField(null=True, upload_to=portfolioapp.models.photo_path)),
                ('url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='testimonial',
        ),
    ]
