# Generated by Django 3.2.3 on 2021-06-25 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0024_auto_20210607_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='technologyPersonalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techName', models.CharField(blank=True, choices=[('Python', 'Python'), ('Java', 'Java'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Bootstrap', 'Bootstrap'), ('PostgresSQL', 'PostgresSQL'), ('Django', 'Django'), ('PHP', 'PHP'), ('MongoDB', 'MongoDB'), ('Docker', 'Docker'), ('Javascript', 'Javascript'), ('jQuery', 'jQuery'), ('ReactJS', 'ReactJS'), ('NodeJS', 'NodeJS'), ('SQLite', 'SQLite'), ('REST API', 'REST API'), ('WordPress', 'WordPress'), ('Drupal', 'Drupal'), ('Magento', 'Magento'), ('Figma', 'Figma'), ('C', 'C'), ('C++', 'C++')], max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies_pp', to='portfolioapp.personalprojects')),
            ],
        ),
        migrations.CreateModel(
            name='technologyRecentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techName', models.CharField(blank=True, choices=[('Python', 'Python'), ('Java', 'Java'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Bootstrap', 'Bootstrap'), ('PostgresSQL', 'PostgresSQL'), ('Django', 'Django'), ('PHP', 'PHP'), ('MongoDB', 'MongoDB'), ('Docker', 'Docker'), ('Javascript', 'Javascript'), ('jQuery', 'jQuery'), ('ReactJS', 'ReactJS'), ('NodeJS', 'NodeJS'), ('SQLite', 'SQLite'), ('REST API', 'REST API'), ('WordPress', 'WordPress'), ('Drupal', 'Drupal'), ('Magento', 'Magento'), ('Figma', 'Figma'), ('C', 'C'), ('C++', 'C++')], max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies_rw', to='portfolioapp.recentwork')),
            ],
        ),
        migrations.RemoveField(
            model_name='technology2',
            name='name',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.DeleteModel(
            name='Technology2',
        ),
    ]
